server.port=8085
spring.application.name=backend

# SQLite Veritabanı Bağlantısı
spring.datasource.url=jdbc:sqlite:flora.db

# JPA & Hibernate Ayarları
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.sql.init.mode=always
# Hibernate tabloları kurduktan SONRA data.sql'in çalışmasını sağlar
spring.jpa.defer-datasource-initialization=true

# ========================================================
# OPENTELEMETRY & LGTM / PLG STACK GÖZLEMLEME AYARLARI
# ========================================================

# 1. Actuator Endpointlerini Dışarı Açma (Prometheus metrikleri için)
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true

# 2. Dağıtık İzleme (Tracing) Ayarları
# %100 Örnekleme (Sampling): Gelen tüm isteklerin (trace) kaydını tutar ve Tempo'ya gönderir
management.tracing.sampling.probability=1.0

# Trace verilerinin Docker üzerindeki Tempo'ya hangi endpoint üzerinden uçacağını söylüyoruz
management.otlp.tracing.endpoint=http://localhost:4318/v1/traces

# 3. Log-Trace Korelasyonu (Loki Entegrasyonu İçin Sihirli Satır)
# Konsoldaki log yapısını [UygulamaAdı, TraceId, SpanId] formatına sokar.
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

# Logların proje kök dizinindeki 'logs' klasörünün altına yazılmasını sağlar
logging.file.name=logs/spring-boot.log

# 2. SQL sorgularını standart log formatına dahil ederek INFO/DEBUG seviyesinde basıyoruz
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# 4. Prometheus Metrikleri Ayarları - histogram metrikleri için gerekli ayarlar
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.slas.http.server.requests=0.005, 0.01, 0.025, 0.05, 0.075, 0.1, 0.25, 0.5, 0.75, 1, 2.5, 5, 7.5, 10
# SİHİRLİ SATIR: Metrik isimlerini OpenTelemetry / Prometheus "total" standartlarına çevirir
management.metrics.export.prometheus.compliance-period=2023-12

management.metrics.web.server.request.autotime.enabled=true